import { addDays, format, startOfWeek } from 'date-fns';
import {
  categoryColors,
} from '../constants/calendar.constants';
import type { CalendarEvent } from '../types/calendar.types';

function getWeekDate(offset: number) {
  return format(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), offset), 'yyyy-MM-dd');
}

export function createDemoCalendarEvents(): CalendarEvent[] {
  const timestamp = new Date().toISOString();

  return [
    {
      id: 'demo-memory-event-case-study',
      itemType: 'event',
      title: 'Portfolio case study review',
      date: getWeekDate(-8),
      startTime: '10:00',
      endTime: '11:30',
      category: 'Learning',
      description: 'Tightened the narrative around Atria as a calendar-first planning system.',
      accentColor: categoryColors.Learning,
      completed: true,
      recurrence: 'none',
      recurringCompletions: {},
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'demo-memory-focus-timeline',
      itemType: 'event',
      title: 'Memory timeline architecture',
      date: getWeekDate(-6),
      startTime: '13:00',
      endTime: '14:30',
      category: 'Work',
      description: 'Mapped a derived timeline from calendar items, intentions, and reflections.',
      accentColor: categoryColors.Work,
      completed: true,
      recurrence: 'none',
      recurringCompletions: {},
      source: 'planning-suggestion',
      focusSession: {
        intentionId: 'demo-intention-memory-foundation',
        planningSuggestionId: 'demo-suggestion-memory-foundation',
      },
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'demo-memory-focus-case-study',
      itemType: 'event',
      title: 'Case study writing focus',
      date: getWeekDate(-10),
      startTime: '09:00',
      endTime: '10:00',
      category: 'Learning',
      description: 'Wrote the problem framing and product principles.',
      accentColor: categoryColors.Learning,
      completed: true,
      recurrence: 'none',
      recurringCompletions: {},
      source: 'planning-suggestion',
      focusSession: {
        intentionId: 'demo-intention-case-study-complete',
        planningSuggestionId: 'demo-suggestion-case-study-writing',
      },
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'demo-memory-focus-demo-flow',
      itemType: 'event',
      title: 'Demo flow focus',
      date: getWeekDate(-9),
      startTime: '09:30',
      endTime: '10:30',
      category: 'Work',
      description: 'Rehearsed the path from Today through Projects and Memories.',
      accentColor: categoryColors.Work,
      completed: true,
      recurrence: 'none',
      recurringCompletions: {},
      source: 'planning-suggestion',
      focusSession: {
        intentionId: 'demo-intention-case-study-complete',
        planningSuggestionId: 'demo-suggestion-demo-flow',
      },
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'demo-memory-recovery-walk',
      itemType: 'event',
      title: 'Recovery walk',
      date: getWeekDate(-5),
      startTime: '18:00',
      endTime: '18:35',
      category: 'Health',
      description: 'Low-stimulation walk after a heavy build day.',
      accentColor: categoryColors.Health,
      completed: true,
      recurrence: 'none',
      recurringCompletions: {},
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'demo-memory-restore-block',
      itemType: 'event',
      title: 'Restore block',
      date: getWeekDate(-4),
      startTime: '17:30',
      endTime: '18:00',
      category: 'Health',
      description: 'Short reset before evening admin.',
      accentColor: categoryColors.Health,
      completed: true,
      recurrence: 'none',
      recurringCompletions: {},
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'demo-memory-recurring-review',
      itemType: 'event',
      title: 'Quiet weekly review',
      date: getWeekDate(-14),
      startTime: '16:00',
      endTime: '16:45',
      category: 'Personal',
      description: 'Looked back at what felt clear, heavy, and worth carrying forward.',
      accentColor: categoryColors.Personal,
      completed: true,
      recurrence: 'weekly',
      recurringCompletions: {
        [getWeekDate(-14)]: true,
        [getWeekDate(-7)]: true,
      },
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'demo-event-1',
      itemType: 'event',
      title: 'Product strategy review',
      date: getWeekDate(0),
      startTime: '09:00',
      endTime: '10:15',
      category: 'Work',
      description: 'Lock weekly priorities and roadmap narrative for the launch ops stream.',
      accentColor: categoryColors.Work,
      completed: false,
      recurrence: 'none',
      recurringCompletions: {},
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'demo-event-standup',
      itemType: 'event',
      title: 'Launch standup',
      date: getWeekDate(0),
      startTime: '13:00',
      endTime: '13:30',
      category: 'Work',
      description: 'Quick decision check before implementation work.',
      accentColor: categoryColors.Work,
      completed: true,
      recurrence: 'daily',
      recurringCompletions: {
        [getWeekDate(0)]: true,
      },
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'demo-task-1',
      itemType: 'task',
      title: 'Draft launch checklist',
      date: getWeekDate(0),
      category: 'Work',
      description: 'Keep it crisp enough to skim before standup.',
      accentColor: categoryColors.Work,
      completed: false,
      recurrence: 'weekly',
      recurringCompletions: {},
      goalId: 'demo-goal-launch-portfolio',
      projectId: 'demo-project-launch-ops',
      order: 0,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'demo-event-2',
      itemType: 'event',
      title: 'Design systems deep work',
      date: getWeekDate(1),
      startTime: '11:00',
      endTime: '12:30',
      category: 'Learning',
      description: 'Refine interaction states and motion principles.',
      accentColor: categoryColors.Learning,
      completed: false,
      recurrence: 'weekly',
      recurringCompletions: {
        [getWeekDate(1)]: true,
      },
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'demo-task-case-study-outline',
      itemType: 'task',
      title: 'Outline portfolio case study',
      date: getWeekDate(1),
      category: 'Learning',
      description: 'Frame problem, product decisions, and final interaction moments.',
      accentColor: categoryColors.Learning,
      completed: true,
      recurrence: 'none',
      recurringCompletions: {},
      goalId: 'demo-goal-launch-portfolio',
      projectId: 'demo-project-atria-case-study',
      order: 1,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'demo-task-2',
      itemType: 'task',
      title: 'Book physiotherapy session',
      date: getWeekDate(1),
      category: 'Health',
      description: '',
      accentColor: categoryColors.Health,
      completed: true,
      recurrence: 'none',
      recurringCompletions: {},
      goalId: 'demo-goal-health-rhythm',
      projectId: 'demo-project-weekly-training',
      order: 0,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'demo-event-3',
      itemType: 'event',
      title: 'Investor update writing',
      date: getWeekDate(2),
      startTime: '14:00',
      endTime: '15:00',
      category: 'Finance',
      description: 'Summarize traction, risks, and next milestones.',
      accentColor: categoryColors.Finance,
      completed: false,
      recurrence: 'none',
      recurringCompletions: {},
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'demo-task-3',
      itemType: 'task',
      title: 'Review prototype feedback',
      date: getWeekDate(2),
      category: 'Work',
      description: 'Extract repeated notes into product decisions.',
      accentColor: categoryColors.Work,
      completed: false,
      recurrence: 'none',
      recurringCompletions: {},
      goalId: 'demo-goal-launch-portfolio',
      projectId: 'demo-project-atria-case-study',
      order: 0,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'demo-event-4',
      itemType: 'event',
      title: 'Strength training',
      date: getWeekDate(3),
      startTime: '18:00',
      endTime: '19:00',
      category: 'Fitness',
      description: 'Lower body session, keep it light.',
      accentColor: categoryColors.Fitness,
      completed: false,
      recurrence: 'weekly',
      recurringCompletions: {
        [getWeekDate(3)]: true,
      },
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'demo-task-training-notes',
      itemType: 'task',
      title: 'Log training notes',
      date: getWeekDate(3),
      category: 'Fitness',
      description: 'Capture load, recovery, and next adjustment.',
      accentColor: categoryColors.Fitness,
      completed: false,
      recurrence: 'weekly',
      recurringCompletions: {},
      goalId: 'demo-goal-health-rhythm',
      projectId: 'demo-project-weekly-training',
      order: 1,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'demo-task-4',
      itemType: 'task',
      title: 'Plan Sunday reset',
      date: getWeekDate(4),
      category: 'Personal',
      description: '',
      accentColor: categoryColors.Personal,
      completed: false,
      recurrence: 'daily',
      recurringCompletions: {
        [getWeekDate(4)]: true,
      },
      goalId: 'demo-goal-health-rhythm',
      order: 0,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'demo-event-5',
      itemType: 'event',
      title: 'Portfolio recording',
      date: getWeekDate(5),
      startTime: '10:30',
      endTime: '11:30',
      category: 'Learning',
      description: 'Capture a clean walkthrough of Atria.',
      accentColor: categoryColors.Learning,
      completed: false,
      recurrence: 'none',
      recurringCompletions: {},
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'demo-task-deploy-notes',
      itemType: 'task',
      title: 'Write deployment notes',
      date: getWeekDate(5),
      category: 'Work',
      description: 'Capture Vercel setup, data limits, and demo caveats.',
      accentColor: categoryColors.Work,
      completed: false,
      recurrence: 'none',
      recurringCompletions: {},
      goalId: 'demo-goal-launch-portfolio',
      projectId: 'demo-project-launch-ops',
      order: 0,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'demo-event-weekly-review',
      itemType: 'event',
      title: 'Weekly review',
      date: getWeekDate(6),
      startTime: '16:00',
      endTime: '17:00',
      category: 'Personal',
      description: 'Scan tasks, goals, projects, and next-week energy.',
      accentColor: categoryColors.Personal,
      completed: false,
      recurrence: 'weekly',
      recurringCompletions: {},
      createdAt: timestamp,
      updatedAt: timestamp,
    },
  ];
}
