import { addDays, format, startOfWeek } from 'date-fns';
import {
  categoryColors,
} from '../constants/calendar.constants';
import type { CalendarEvent } from '../types/calendar.types';

function getWeekDate(offset: number) {
  return format(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), offset), 'yyyy-MM-dd');
}

export function createDemoCalendarEvents(): CalendarEvent[] {
  const timestamp = new Date().toISOString();

  return [
    {
      id: 'demo-event-1',
      itemType: 'event',
      title: 'Product strategy review',
      date: getWeekDate(0),
      startTime: '09:00',
      endTime: '10:15',
      category: 'Work',
      description: 'Lock weekly priorities and roadmap narrative.',
      accentColor: categoryColors.Work,
      completed: false,
      recurrence: 'none',
      recurringCompletions: {},
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'demo-task-1',
      itemType: 'task',
      title: 'Draft launch checklist',
      date: getWeekDate(0),
      category: 'Work',
      description: 'Keep it crisp enough to skim before standup.',
      accentColor: categoryColors.Work,
      completed: false,
      recurrence: 'weekly',
      recurringCompletions: {},
      order: 0,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'demo-event-2',
      itemType: 'event',
      title: 'Design systems deep work',
      date: getWeekDate(1),
      startTime: '11:00',
      endTime: '12:30',
      category: 'Learning',
      description: 'Refine interaction states and motion principles.',
      accentColor: categoryColors.Learning,
      completed: false,
      recurrence: 'weekly',
      recurringCompletions: {},
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'demo-task-2',
      itemType: 'task',
      title: 'Book physiotherapy session',
      date: getWeekDate(1),
      category: 'Health',
      description: '',
      accentColor: categoryColors.Health,
      completed: true,
      recurrence: 'none',
      recurringCompletions: {},
      order: 0,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'demo-event-3',
      itemType: 'event',
      title: 'Investor update writing',
      date: getWeekDate(2),
      startTime: '14:00',
      endTime: '15:00',
      category: 'Finance',
      description: 'Summarize traction, risks, and next milestones.',
      accentColor: categoryColors.Finance,
      completed: false,
      recurrence: 'none',
      recurringCompletions: {},
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'demo-task-3',
      itemType: 'task',
      title: 'Review prototype feedback',
      date: getWeekDate(2),
      category: 'Work',
      description: 'Extract repeated notes into product decisions.',
      accentColor: categoryColors.Work,
      completed: false,
      recurrence: 'none',
      recurringCompletions: {},
      order: 0,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'demo-event-4',
      itemType: 'event',
      title: 'Strength training',
      date: getWeekDate(3),
      startTime: '18:00',
      endTime: '19:00',
      category: 'Fitness',
      description: 'Lower body session, keep it light.',
      accentColor: categoryColors.Fitness,
      completed: false,
      recurrence: 'weekly',
      recurringCompletions: {},
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'demo-task-4',
      itemType: 'task',
      title: 'Plan Sunday reset',
      date: getWeekDate(4),
      category: 'Personal',
      description: '',
      accentColor: categoryColors.Personal,
      completed: false,
      recurrence: 'daily',
      recurringCompletions: {},
      order: 0,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'demo-event-5',
      itemType: 'event',
      title: 'Portfolio recording',
      date: getWeekDate(5),
      startTime: '10:30',
      endTime: '11:30',
      category: 'Learning',
      description: 'Capture a clean walkthrough of Atria.',
      accentColor: categoryColors.Learning,
      completed: false,
      recurrence: 'none',
      recurringCompletions: {},
      createdAt: timestamp,
      updatedAt: timestamp,
    },
  ];
}
